@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
' uncomment the following line and comment the first to use locally
' !include C4_Container.puml

' LAYOUT_TOP_DOWN()
' LAYOUT_AS_SKETCH()
LAYOUT_WITH_LEGEND()

title Container diagram for Shopping List Web App  Deployed on Local Machine

Person(user, "User", "An user who intends to create or manage a shopping list.")
Person(admin, "Admin", "An administrator responsible for overseeing and managing shopping list data.")

System_Boundary(system-boundary, "Shopping List Web App") {
    Container(shoppingListFrontEnd, "Shopping List Front End", "vue.js 3.3.4", "A web interface allowing users to interact with and manage their shopping lists.")
    Container(shoppingListApi, "Shopping List API", "Spring boot 3.1.4", "An API layter facilitating operations on shopping list items and interfacing between the front end and the database.")
    Container(postgres, "PostgreSQL Database", "PostgreSQL 15.4", "The database storing all shopping list data.")
    Container(pgadmin, "pgAdmin PostgreSQL Tools", "pgadmin 4", "A management tool for the Postgres database, allowing administrators to manage shopping list data directly.")
}

Rel(user, shoppingListFrontEnd, "Views and modifies shopping lists", "JSON/HTTP")
Rel(admin, pgadmin, "Manages shopping list data", "HTTP")

Rel(shoppingListFrontEnd, shoppingListApi, "Sends requests to manage shopping items", "JSON/HTTP")
Rel(shoppingListApi, postgres, "Queries and updates shopping data", "JDBC")
Rel(pgadmin, postgres, "Manages data in database", "PostgresSQL protocol")

@enduml