CREATE TABLE shopping_item
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title     VARCHAR(255)                            NOT NULL,
    purchased BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_shopping_item PRIMARY KEY (id)
);